#!/usr/bin/env bash

# TODO:
# - Add something that shows the progress
# - be able to toggle the build info prompt on/off
# - be able to toggle the auto git pull off
# - remove the git pull hint prompt, and make it auto overwrite the previous repository
# BUGS:
# gnutls_handshake() error when git pulling

GitRepoList=(
    "https://github.com/radinals/dwm.git"
    "https://github.com/radinals/dwmblocks.git"
    "https://github.com/radinals/dmenu.git"
    "https://github.com/radinals/st.git"
    "https://github.com/fulhax/ncpamixer"
    "https://github.com/himdel/hsetroot.git"
    "https://github.com/neovim/neovim.git")

BuildDeps=(
    "libxinerama-dev" "libimlib2-dev" "libx11-dev" "libxinerama-dev"
    "pkg-config" "pulseaudio" "libncurses-dev" "libpulse-dev"
    "libxft-dev" "ninja-build" "gettext" "libtool"
    "libtool-bin" "autoconf" "automake" "cmake" "g++" "unzip"
    "libgdk-pixbuf-xlib-2.0-0" "curl" "doxygen")

InstallPkg(){ apt-get -y install "$1" >/dev/null 2>&1; }

error(){ printf "%s\n" "##### $1 #####" >&2; exit 1; }

GitCloneRepo(){
    if [ ! -d "$1" ]; then
	printf "%s\n" "Git cloning repository..." && \
	    git clone "$2" "$1" && printf "%s\n" "Repo Cloned..."
    else
	printf "%s\n" "Checking for updates..."
	cd "$1" || exit 1
	git pull
    fi
    printf "\n" 
}

MakePkg(){
    cd "$1" || exit 1
    printf "%s\n" "Building..."
    sudo make >/dev/null 2>&1
    sudo make install
    printf "%s\n" "Build complete..."
    printf "\n" 
}

MakeNvim(){
    cd "$1" || exit 1
    printf "%s\n" "Building neovim stable..."
    git checkout stable
    sudo make CMAKE_BUILD_TYPE=Release >/dev/null 2>&1
    sudo make install
    printf "%s\n" "Build complete..."
    printf "\n"
}

InstallPacker(){
    if [ ! -d "$HOME/.local/share/nvim/site/pack/packer" ]; then
	read -p "Install packer?" ConfirmInstall
	if [ "${ConfirmInstall^^}" == "Y" ]; then
	    git clone --depth 1 https://github.com/wbthomason/packer.nvim\
		~/.local/share/nvim/site/pack/packer/start/packer.nvim && \
		printf "%s\n" "Packer installed..."
	else
	    printf "%s\n" "Not Installing Packer..."
	fi

    else
	printf "%s\n" "Packer already installed..."

    fi
}

GetProgDeps(){
    DepPkg=$1

    [ "$(dpkg-query -W -f='${status}' "${DepPkg[@]}" 2>/dev/null | grep -c "ok installed")" -lt "${#DepPkg[@]}" ] && \
	printf "%s\n" "Installing Package Dependencies..."
	sudo InstallPkg "${DepPkg[@]}"
}

GitMakeInstall(){
    ProgRepo="$1"
    ProgDeps="$2"
    SourceDir="/usr/local/src"
    ProgName=$(basename "$ProgRepo" .git)

    [ -z "$ProgName" ] && error "Missing the program name!."
    [ -z "$ProgRepo" ] && error "Missing the program repository link!."

    [ ! -d "$SourceDir" ] && mkdir -p "$SourceDir"

    printf "%s\n" "##### $ProgName #####"
    GetProgDeps "$ProgDeps"
    GitCloneRepo "$SourceDir/$ProgName" "$ProgRepo"

    if [ "$ProgName" == "neovim" ]; then
	MakeNvim "$SourceDir/$ProgName"
	InstallPacker
    else
	MakePkg "$SourceDir/$ProgName"
    fi
}

InstallGitPkg(){
    for r in "${GitRepoList[@]}"; do
        GitMakeInstall "$r" "${BuildDeps[@]}"
    done
}

# InstallScripts()
# InstallDotfiles()
# InstallWallpapers()
# InstallExtraPkg()

InstallGitPkg
